import type { FullAnalysisResult } from '@/lib/layoutEngine'

interface Pt { x: number; y: number }

// ── DXF R12 text generation helpers ──────────────────────────────

function grp(...pairs: (string | number)[]): string {
  const parts: string[] = []
  for (let i = 0; i < pairs.length; i += 2) {
    parts.push(String(pairs[i]), String(pairs[i + 1]))
  }
  return parts.join('\n')
}

function dxfPolyline(layer: string, pts: Pt[], closed = true): string {
  const lines: string[] = [
    grp(0, 'POLYLINE', 8, layer, 66, 1, 10, '0.0', 20, '0.0', 30, '0.0', 70, closed ? 1 : 0),
  ]
  for (const p of pts) {
    lines.push(grp(0, 'VERTEX', 8, layer, 10, p.x.toFixed(4), 20, p.y.toFixed(4), 30, '0.0', 70, 0))
  }
  lines.push(grp(0, 'SEQEND', 8, layer))
  return lines.join('\n')
}

function dxfText(layer: string, x: number, y: number, txt: string, h = 1.5): string {
  return grp(0, 'TEXT', 8, layer, 10, x.toFixed(3), 20, y.toFixed(3), 30, '0.0', 40, h, 1, txt)
}

function dxfLtype(name: string, desc: string, elements: number[]): string {
  const total = elements.reduce((s, v) => s + Math.abs(v), 0)
  const base = grp(0, 'LTYPE', 2, name, 70, 0, 3, desc, 72, 65, 73, elements.length, 40, total.toFixed(3))
  if (elements.length === 0) return base
  return base + '\n' + elements.map(e => `49\n${e}`).join('\n')
}

function dxfLayer(name: string, color: number, ltype = 'CONTINUOUS'): string {
  return grp(0, 'LAYER', 2, name, 70, 0, 62, color, 6, ltype)
}

// ── Main export function ──────────────────────────────────────────

export function exportDXF(
  zones: FullAnalysisResult[],
  filename: string,
  meta?: { author?: string; company?: string },
): void {
  // Compute bounding box for EXTMIN/EXTMAX
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
  for (const zone of zones) {
    for (const p of zone.safeZone.originalPolygon) {
      if (p.x < minX) minX = p.x; if (p.x > maxX) maxX = p.x
      if (p.y < minY) minY = p.y; if (p.y > maxY) maxY = p.y
    }
  }
  const pad = Math.max(maxX - minX, maxY - minY, 10) * 0.15

  const header = [
    grp(0, 'SECTION', 2, 'HEADER'),
    grp(9, '$ACADVER', 1, 'AC1009'),     // DXF R12
    grp(9, '$INSUNITS', 70, 6),          // 6 = meters
    grp(9, '$EXTMIN', 10, (minX - pad).toFixed(2), 20, (minY - pad).toFixed(2), 30, '0.0'),
    grp(9, '$EXTMAX', 10, (maxX + pad).toFixed(2), 20, (maxY + pad).toFixed(2), 30, '0.0'),
    grp(0, 'ENDSEC'),
  ].join('\n')

  const tables = [
    grp(0, 'SECTION', 2, 'TABLES'),
    // LTYPE table
    grp(0, 'TABLE', 2, 'LTYPE', 70, 2),
    dxfLtype('CONTINUOUS', 'Solid line', []),
    dxfLtype('DASHED', 'Dashed __  __  __', [0.5, -0.25]),
    grp(0, 'ENDTABLE'),
    // LAYER table
    grp(0, 'TABLE', 2, 'LAYER', 70, 4),
    dxfLayer('BOUNDARY', 7),              // 7=white/black
    dxfLayer('SAFE_ZONE', 3, 'DASHED'),   // 3=green, dashed
    dxfLayer('PANELS', 2),                // 2=yellow
    dxfLayer('TEXT_INFO', 7),
    grp(0, 'ENDTABLE'),
    grp(0, 'ENDSEC'),
  ].join('\n')

  const entities: string[] = [grp(0, 'SECTION', 2, 'ENTITIES')]

  for (const zone of zones) {
    const boundary = zone.safeZone.originalPolygon
    if (boundary.length >= 3) entities.push(dxfPolyline('BOUNDARY', boundary))

    const safe = zone.safeZone.safeZonePolygon
    if (safe && safe.length >= 3) entities.push(dxfPolyline('SAFE_ZONE', safe))

    for (const p of zone.layout.placements) {
      entities.push(dxfPolyline('PANELS', [...p.corners]))
    }
  }

  // Summary text below drawing
  const totalCount = zones.reduce((s, z) => s + z.layout.totalCount, 0)
  const totalKwp = zones.reduce((s, z) => s + z.layout.totalKwp, 0)
  const ref = zones[0]
  const cx = (minX + maxX) / 2
  const textY = minY - pad * 0.5

  const authorLine = [meta?.author, meta?.company].filter(Boolean).join(' / ')
  const infoLines = [
    `Panels: ${totalCount}  Capacity: ${totalKwp.toFixed(2)} kWp`,
    `Tilt: ${ref.optimalTilt}deg  Azimuth: ${ref.azimuthDeg}deg  Row Spacing: ${ref.rowSpacing.toFixed(2)}m`,
    authorLine ? `Author: ${authorLine}  |  Generated by SolarAdvisor` : `Generated by SolarAdvisor`,
  ]
  infoLines.forEach((line, i) => {
    entities.push(dxfText('TEXT_INFO', cx, textY - i * (pad * 0.15), line, pad * 0.08))
  })

  entities.push(grp(0, 'ENDSEC'), grp(0, 'EOF'))

  const dxf = [header, tables, ...entities].join('\n')
  const blob = new Blob([dxf], { type: 'application/dxf;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
